[[redirects]]
  from = "/terms.html"
  to = "/terms"
  status = 301

[[redirects]]
  from = "/privacy.html"
  to = "/privacy"
  status = 301

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

[[headers]]
  for = "/webdemo/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"

[[headers]]
  for = "/webdemo/*.pck"
  [headers.values]
    Content-Type = "application/octet-stream"
